import {
  PxAlert,
  PxBadge,
  PxButton,
  PxButtonGroup,
  PxCollapse,
  PxCollapseItem,
  PxConfigProvider,
  PxDropdown,
  PxDropdownItem,
  PxForm,
  PxFormItem,
  PxIcon,
  PxInput,
  PxLoading,
  PxMessage,
  PxMessageBox,
  PxNotification,
  PxOption,
  PxPopconfirm,
  PxSelect,
  PxSwitch,
  PxTooltip,
} from '@sakana-element/components';
import type { Plugin } from 'vue';

export default [
  PxBadge,
  PxButton,
  PxButtonGroup,
  PxIcon,
  PxCollapse,
  PxCollapseItem,
  PxAlert,
  PxTooltip,
  PxPopconfirm,
  PxDropdown,
  PxDropdownItem,
  PxMessage,
  PxNotification,
  PxInput,
  PxMessageBox,
  PxLoading,
  PxSwitch,
  PxSelect,
  PxOption,
  PxForm,
  PxFormItem,
  PxConfigProvider,
] as Plugin[]; //为了方便使用，我们将所有组件导出为一个数组，这样在使用时只需要导入这个数组即可。
